# Generated by Django 2.1.3 on 2018-12-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='alert',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
